### ISSUE TITLE
`SLOW TEST RUN` showing on fast tests

### ISSUE THREAD

**Issue by danielcompton** [yeller/bolth#5]
I got these results on some tests I was running. They seem to be plenty fast, so I don't quite understand why "SLOW TEST RUN" is printing. I took a brief look at the code and it seemed ok. Is this expected behaviour? If not I can dig in to find a fix.

```
running...
............

FAIL in clojure.lang.PersistentList$EmptyList@1 (bob_test.clj:45)

expected: "Sure."
  actual: "Whoa, chill out!"
    diff: - "Sure."
          + "Whoa, chill out!"


FAIL in clojure.lang.PersistentList$EmptyList@1 (bob_test.clj:42)

expected: "Whatever."
  actual: "Whoa, chill out!"
    diff: - "Whatever."
          + "Whoa, chill out!"


12 passes, 2 failures, 14 assertions
14.60ms, 1.04ms per test
SLOW TEST RUN
```

**Comment by tom-pang** [comment]
that isn't expected, would be happy for you to take a look. Note that bolth has had some substantial changes in the https://github.com/yeller/bolth/tree/bolth2 branch, but it should be easy enough to forward port em.

**Comment by tom-pang** [comment]
also you'll note these tests include `clojure.lang.PersistentList$EmptyList@1` - that's a bug, fixed in `bolth2` (see the branch)

**Comment by tom-pang** [comment]
@danielcompton did you get a chance to look here? I ain't been able to reproduce this locally :(

**Comment by danielcompton** [comment]
I was waiting to check it on bolth 2. I've upgraded today and it's still failing, so I'll dig in to see what's happening:

```
running...
.......................

23 passes, 0 failures, 23 assertions
35.80ms, 1.56ms per test
SLOW TEST RUN
slowest 10 tests were:
1. rethink-proxy.test.sites/matches-site in 6.89ms
2. rethink-proxy.test.queries/query-terms in 4.84ms
3. rethink-proxy.test.queries/query-safe? in 2.99ms
4. rethink-proxy.test.sites/not-matches-site in 2.84ms
```

**Comment by danielcompton** [comment]
I think I've found the issue, PEBKAC. 

I expected that `:warn-on-slow-test-limit-ms 10` would warn me if any individual test ran over 10 ms. However that's used for warning if the total test runtime limit was over 10 ms. That also explains why I was confused about seeing `slowest n tests` when each test runtime was under my `:warn-on-slow-test-limit-ms` value.

I think it could be helpful to set a slow test threshold, so you only see slow tests when they show up over your threshold. This would maximise signal to noise ratio of `slowest n tests were` section. But it does change the intent a little.
